import { afterEach, describe, expect, it, vi } from 'vitest'
import { useActivityToastStack } from '~/composables/useActivityToastStack'
const toast = (id: string) => ({ id, kind: 'generic', title: id, context: 'Notification', to: '/notifications' })
afterEach(() => vi.useRealTimers())
describe('temporary activity stack', () => {
  it('keeps three with newest at bottom and evicts the oldest without replaying duplicates', () => {
    vi.useFakeTimers()
    const stack = useActivityToastStack()
    for (const id of ['a','b','c','d']) stack.push(toast(id))
    expect(stack.toasts.value.map(item => item.id)).toEqual(['b','c','d'])
    expect(stack.push(toast('a'))).toBe(false)
    vi.advanceTimersByTime(6000)
    expect(stack.toasts.value).toEqual([])
  })
  it('preserves remaining time across pointer and keyboard pause and protects a focused oldest card', () => {
    vi.useFakeTimers()
    const stack = useActivityToastStack()
    stack.push(toast('a'))
    vi.advanceTimersByTime(2000)
    stack.pause('a','hovered',true)
    stack.pause('a','focused',true)
    stack.pause('a','hovered',false)
    vi.advanceTimersByTime(10000)
    expect(stack.toasts.value).toHaveLength(1)
    stack.push(toast('b')); stack.push(toast('c'))
    expect(stack.push(toast('d'))).toBe(false)
    stack.pause('a','focused',false)
    vi.advanceTimersByTime(3999)
    expect(stack.toasts.value[0]?.id).toBe('a')
    vi.advanceTimersByTime(1)
    expect(stack.toasts.value.map(item => item.id)).toEqual(['b','c'])
    stack.clear(true)
    expect(stack.push(toast('a'))).toBe(true)
    stack.clear()
  })
})
