import type { useChatPageState } from './useChatPage'
import type { useChatPageView } from './useChatPageView'

/** Explicit capabilities of each chat phase; unrelated mutable state stays private. */
export type ChatViewContext = Pick<ReturnType<typeof useChatPageState>,
  | 'apiFetch'
  | 'apiFetchData'
  | 'route'
  | 'me'
  | 'viewerCanStartChats'
  | 'addInterest'
  | 'removeInterest'
  | 'suppressMessageUnreadBumpsForMs'
  | 'marv'
  | 'selectedConversationId'
  | 'selectedChatKey'
  | 'atBottom'
  | 'stickToBottom'
  | 'setAtBottomState'
  | 'scrollEventHandler'
  | 'conversationsApi'
  | 'selectedConversation'
  | 'patchConversation'
  | 'removeConversationFromList'
  | 'updateConversationParticipantRead'
  | 'updateConversationUnread'
  | 'updateConversationForMessage'
  | 'markConversationReadIfVisible'
  | 'getMessageTier'
  | 'getDirectUser'
  | 'getConversationLastMessageTier'
  | 'lastVisibleMessageSnapshot'
  | 'showCantStartChat'
  | 'thread'
  | 'messages'
  | 'infoMessage'
  | 'sendingMessageIds'
  | 'setRemoteTyping'
  | 'routeSync'
  | 'surfaceOptions'
  | 'isViewingSurface'
>

export type ChatLifecycleContext = Pick<ReturnType<typeof useChatPageState> & ReturnType<typeof useChatPageView>,
  | 'route'
  | 'ensureLoaded'
  | 'viewerCanUseChat'
  | 'prefersReducedMotion'
  | 'chatBootState'
  | 'clearChatBootTimer'
  | 'revealChatScreenAfterFade'
  | 'isSocketConnected'
  | 'emitMessagesScreen'
  | 'marv'
  | 'selectedConversationId'
  | 'selectedChatKey'
  | 'isDraftChat'
  | 'messagesScroller'
  | 'composerBarRef'
  | 'scrollApi'
  | 'onMessagesScrollerMounted'
  | 'conversationsApi'
  | 'activeTab'
  | 'conversations'
  | 'activeList'
  | 'listLoading'
  | 'listFailed'
  | 'fetchConversations'
  | 'thread'
  | 'messages'
  | 'messagesLoading'
  | 'jumpTargetMessageId'
  | 'renderedChatKey'
  | 'messagesPaneState'
  | 'routeSync'
  | 'selectConversation'
  | 'isTabBarMode'
  | 'isTinyViewport'
  | 'registerRealtime'
  | 'teardownRealtime'
  | 'me'
  | 'surfaceOptions'
  | 'isViewingSurface'
  | 'isLatestWindow'
  | 'atBottom'
>

