import { describe, expect, it, vi } from 'vitest'
import { MediaFocus } from '../../utils/mediaFocus'

describe('app media focus', () => {
  it('keeps paused voice selected against autoplay and hands off to explicit video', () => {
    const focus = new MediaFocus()
    const stopVoice = vi.fn()
    expect(focus.claim('voice', stopVoice)).toBe(true)
    expect(focus.claim('video:auto', vi.fn(), { automatic: true })).toBe(false)
    expect(stopVoice).not.toHaveBeenCalled()
    expect(focus.claim('video:manual', vi.fn())).toBe(true)
    expect(stopVoice).toHaveBeenCalledTimes(1)
    focus.release('voice')
    expect(focus.currentId).toBe('video:manual')
  })
  it('keeps calls separate from media while protecting microphone capture', () => {
    const focus = new MediaFocus()
    const stopVoice = vi.fn()
    focus.claim('voice', stopVoice)
    focus.setCallActive(true)
    expect(stopVoice).not.toHaveBeenCalled()
    expect(focus.currentId).toBe('voice')
    expect(focus.claim('video:manual', vi.fn())).toBe(true)
    expect(stopVoice).toHaveBeenCalledOnce()
    expect(focus.claim('recording', vi.fn(), { exclusive: true })).toBe(false)
    focus.setCallActive(false)
    expect(focus.currentId).toBe('video:manual')
    expect(focus.claim('recording', vi.fn(), { exclusive: true })).toBe(true)
  })
  it('cancels a pending recording when a call starts without reserving media focus', () => {
    const focus = new MediaFocus()
    const cancel = vi.fn()
    focus.claim('recording', cancel, { exclusive: true })
    focus.setCallActive(true)
    expect(cancel).toHaveBeenCalledOnce()
    expect(focus.currentId).toBeNull()
    expect(focus.claim('voice', vi.fn())).toBe(true)
  })
  it('notifies subscribers and resets ownership safely when stop releases old focus', () => {
    const focus = new MediaFocus()
    const changes = vi.fn()
    const dispose = focus.subscribe(changes)
    focus.claim('radio', () => focus.release('radio'))
    focus.claim('voice', vi.fn())
    expect(focus.currentId).toBe('voice')
    expect(changes).toHaveBeenLastCalledWith('voice')
    focus.reset()
    expect(focus.currentId).toBeNull()
    dispose()
  })
})
