export const interestOptions: Array<{ value: string; label: string }> = [
  // Shared / meetup-style interests (helps guys find "their people")
  { value: 'weightlifting', label: 'Weightlifting' },
  { value: 'powerlifting', label: 'Powerlifting' },
  { value: 'bodybuilding', label: 'Bodybuilding' },
  { value: 'crossfit', label: 'CrossFit' },
  { value: 'running', label: 'Running' },
  { value: 'hiking', label: 'Hiking' },
  { value: 'cycling', label: 'Cycling' },
  { value: 'basketball', label: 'Basketball' },
  { value: 'soccer', label: 'Soccer' },
  { value: 'golf', label: 'Golf' },
  { value: 'martial_arts', label: 'Martial arts' },
  { value: 'boxing', label: 'Boxing' },
  { value: 'jiu_jitsu', label: 'Jiu-jitsu' },
  { value: 'hunting', label: 'Hunting' },
  { value: 'fishing', label: 'Fishing' },
  { value: 'camping', label: 'Camping' },
  { value: 'motorcycles', label: 'Motorcycles' },
  { value: 'cars', label: 'Cars' },
  { value: 'entrepreneurship', label: 'Entrepreneurship' },
  { value: 'investing', label: 'Investing' },
  { value: 'tech', label: 'Tech' },
  { value: 'gaming', label: 'Gaming' },
  { value: 'books', label: 'Books' },
  { value: 'faith', label: 'Faith' },
  { value: 'volunteering', label: 'Volunteering' },
  { value: 'fatherhood', label: 'Fatherhood' },
  { value: 'mens_groups', label: "Men's groups" },
]

