export type InterestOption = { value: string; label: string; group: string; keywords?: string[] }

export const interestGroupKeywords: Record<string, string[]> = {
  Religion: ['religion', 'faith', 'spiritual', 'spirituality', 'god', 'church', 'bible', 'prayer', 'theology'],
  Politics: ['politics', 'news', 'current events', 'government', 'policy', 'elections', 'law', 'taxes', 'geopolitics'],
  Business: ['business', 'money', 'finance', 'investing', 'career', 'leadership', 'management', 'marketing', 'sales', 'crypto', 'productivity'],
  Technology: ['tech', 'technology', 'software', 'coding', 'programming', 'ai', 'security', 'cloud', 'devops', 'data'],
  Health: ['health', 'fitness', 'gym', 'strength', 'cardio', 'nutrition', 'sleep', 'recovery', 'mental health', 'mobility', 'longevity'],
  Relationships: ['relationships', 'dating', 'marriage', 'family', 'fatherhood', 'friendship', 'community', 'mentorship', 'communication', 'boundaries'],
  Philosophy: ['philosophy', 'meaning', 'purpose', 'ethics', 'stoicism', 'discipline', 'habits', 'psychology', 'learning'],
}

export const interestGroupOrder = [
  'Religion',
  'Politics',
  'Business',
  'Technology',
  'Health',
  'Relationships',
  'Philosophy',
] as const

export const interestOptions: InterestOption[] = [
  // Religion (14)
  { value: 'faith', label: 'Faith', group: 'Religion', keywords: ['religion', 'spiritual', 'spirituality', 'god', 'church'] },
  { value: 'christianity', label: 'Christianity', group: 'Religion', keywords: ['christian', 'jesus', 'christ'] },
  { value: 'bible', label: 'Bible', group: 'Religion', keywords: ['bible study', 'scripture'] },
  { value: 'prayer', label: 'Prayer', group: 'Religion', keywords: ['pray', 'praying'] },
  { value: 'church', label: 'Church', group: 'Religion', keywords: ['worship', 'sermon', 'congregation', 'fellowship'] },
  { value: 'theology', label: 'Theology', group: 'Religion', keywords: ['doctrine'] },
  { value: 'apologetics', label: 'Apologetics', group: 'Religion', keywords: ['defend the faith'] },
  { value: 'discipleship', label: 'Discipleship', group: 'Religion', keywords: ['sanctification'] },
  { value: 'catholicism', label: 'Catholicism', group: 'Religion', keywords: ['catholic', 'mass', 'rosary', 'pope'] },
  { value: 'protestantism', label: 'Protestantism', group: 'Religion', keywords: ['protestant', 'baptist', 'methodist', 'lutheran', 'evangelical'] },
  { value: 'orthodox_christianity', label: 'Orthodox Christianity', group: 'Religion', keywords: ['orthodox', 'eastern orthodox', 'orthodoxy'] },
  { value: 'islam', label: 'Islam', group: 'Religion', keywords: ['muslim', 'quran', 'koran'] },
  { value: 'judaism', label: 'Judaism', group: 'Religion', keywords: ['jewish', 'torah'] },
  { value: 'buddhism', label: 'Buddhism', group: 'Religion', keywords: ['buddhist', 'dharma'] },

  // Politics (14)
  { value: 'current_events', label: 'Current events', group: 'Politics', keywords: ['news', 'breaking news'] },
  { value: 'politics', label: 'Politics', group: 'Politics', keywords: ['political', 'congress', 'senate'] },
  { value: 'elections', label: 'Elections', group: 'Politics', keywords: ['voting', 'ballot', 'primary'] },
  { value: 'policy', label: 'Policy', group: 'Politics', keywords: ['public policy'] },
  { value: 'law', label: 'Law', group: 'Politics', keywords: ['legal', 'court', 'supreme court'] },
  { value: 'civics', label: 'Civics', group: 'Politics', keywords: ['government', 'constitution'] },
  { value: 'economics', label: 'Economics', group: 'Politics', keywords: ['economy', 'inflation', 'gdp', 'recession'] },
  { value: 'geopolitics', label: 'Geopolitics', group: 'Politics', keywords: ['international relations', 'foreign policy', 'war'] },
  { value: 'media', label: 'Media', group: 'Politics', keywords: ['journalism', 'press'] },
  { value: 'immigration', label: 'Immigration', group: 'Politics', keywords: ['border', 'asylum'] },
  { value: 'education_policy', label: 'Education policy', group: 'Politics', keywords: ['schools', 'school choice'] },
  { value: 'healthcare_policy', label: 'Healthcare policy', group: 'Politics', keywords: ['healthcare', 'medicare', 'medicaid'] },
  { value: 'taxation', label: 'Taxation', group: 'Politics', keywords: ['taxes', 'irs'] },
  { value: 'political_philosophy', label: 'Political philosophy', group: 'Politics', keywords: ['liberalism', 'conservatism', 'libertarian', 'socialism'] },

  // Business (14)
  { value: 'entrepreneurship', label: 'Entrepreneurship', group: 'Business', keywords: ['entrepreneur', 'founder'] },
  { value: 'startups', label: 'Startups', group: 'Business', keywords: ['startup', 'saas', 'bootstrapping'] },
  { value: 'investing', label: 'Investing', group: 'Business', keywords: ['stocks', 'etf', 'index funds', '401k', 'roth', 'dividends'] },
  { value: 'personal_finance', label: 'Personal finance', group: 'Business', keywords: ['budget', 'saving', 'debt', 'credit'] },
  { value: 'real_estate', label: 'Real estate', group: 'Business', keywords: ['realestate', 'mortgage', 'rental property', 'airbnb'] },
  { value: 'career_growth', label: 'Career growth', group: 'Business', keywords: ['career', 'jobs', 'resume', 'interview', 'promotion'] },
  { value: 'leadership', label: 'Leadership', group: 'Business', keywords: ['leading', 'lead'] },
  { value: 'management', label: 'Management', group: 'Business', keywords: ['manager', 'managing'] },
  { value: 'marketing', label: 'Marketing', group: 'Business', keywords: ['brand', 'advertising'] },
  { value: 'sales', label: 'Sales', group: 'Business', keywords: ['selling', 'closing'] },
  { value: 'product_management', label: 'Product management', group: 'Business', keywords: ['pm', 'product manager'] },
  { value: 'small_business', label: 'Small business', group: 'Business', keywords: ['local business'] },
  { value: 'crypto', label: 'Crypto', group: 'Business', keywords: ['cryptocurrency', 'bitcoin', 'btc', 'ethereum', 'eth'] },
  { value: 'productivity', label: 'Productivity', group: 'Business', keywords: ['time management', 'focus'] },

  // Technology (14)
  { value: 'ai', label: 'AI', group: 'Technology', keywords: ['artificial intelligence', 'machine learning', 'ml', 'llm', 'chatgpt', 'openai', 'claude', 'gemini'] },
  { value: 'programming', label: 'Programming', group: 'Technology', keywords: ['coding', 'developer', 'software engineer', 'engineering', 'github', 'open source'] },
  { value: 'web_development', label: 'Web development', group: 'Technology', keywords: ['web dev', 'frontend', 'backend', 'react', 'vue', 'nuxt', 'node'] },
  { value: 'mobile_development', label: 'Mobile development', group: 'Technology', keywords: ['ios', 'android', 'swift', 'kotlin'] },
  { value: 'cybersecurity', label: 'Cybersecurity', group: 'Technology', keywords: ['infosec', 'security', 'pentest', 'vulnerability', 'breach', 'malware', 'ransomware', 'phishing', 'cve', 'ctf'] },
  { value: 'cloud', label: 'Cloud', group: 'Technology', keywords: ['aws', 'gcp', 'azure'] },
  { value: 'devops', label: 'DevOps', group: 'Technology', keywords: ['ci', 'cd', 'kubernetes', 'docker', 'terraform'] },
  { value: 'data_science', label: 'Data science', group: 'Technology', keywords: ['data', 'analytics', 'statistics', 'pandas'] },
  { value: 'hardware', label: 'Hardware', group: 'Technology', keywords: ['pc building', 'chips', 'cpu', 'gpu'] },
  { value: 'gadgets', label: 'Gadgets', group: 'Technology', keywords: ['gear'] },
  { value: 'gaming', label: 'Gaming', group: 'Technology', keywords: ['games', 'video games', 'pc gaming', 'steam', 'xbox', 'playstation', 'ps5', 'nintendo', 'switch'] },
  { value: 'privacy', label: 'Privacy', group: 'Technology', keywords: ['surveillance'] },
  { value: 'open_source', label: 'Open source', group: 'Technology', keywords: ['oss', 'open-source'] },
  { value: 'tech_news', label: 'Tech news', group: 'Technology', keywords: ['technology', 'tech'] },

  // Health (14)
  { value: 'strength_training', label: 'Strength training', group: 'Health', keywords: ['gym', 'strength', 'lifting', 'hypertrophy', 'squat', 'bench', 'deadlift'] },
  { value: 'endurance_training', label: 'Endurance training', group: 'Health', keywords: ['cardio', 'running', 'cycling', 'swimming', 'triathlon', 'rowing', 'marathon', 'ironman'] },
  { value: 'sports', label: 'Sports', group: 'Health', keywords: ['athlete', 'basketball', 'soccer', 'baseball', 'football', 'hockey', 'tennis', 'pickleball', 'golf'] },
  { value: 'combat_sports', label: 'Combat sports', group: 'Health', keywords: ['martial arts', 'boxing', 'kickboxing', 'muay thai', 'mma', 'wrestling', 'judo', 'jiu jitsu', 'bjj'] },
  { value: 'outdoors', label: 'Outdoors', group: 'Health', keywords: ['outdoor', 'nature', 'hiking', 'camping', 'backpacking', 'fishing', 'hunting', 'climbing', 'skiing', 'snowboarding', 'kayaking'] },
  { value: 'nutrition', label: 'Nutrition', group: 'Health', keywords: ['diet', 'macros', 'protein', 'calories', 'keto', 'carnivore', 'intermittent fasting', 'cooking', 'bbq'] },
  { value: 'sleep', label: 'Sleep', group: 'Health', keywords: ['insomnia', 'sleep apnea'] },
  { value: 'mental_health', label: 'Mental health', group: 'Health', keywords: ['therapy', 'anxiety', 'depression', 'counseling'] },
  { value: 'meditation', label: 'Meditation', group: 'Health', keywords: ['mindfulness', 'breathwork', 'breathing'] },
  { value: 'mobility', label: 'Mobility', group: 'Health', keywords: ['stretching', 'range of motion', 'rom', 'foam rolling', 'prehab', 'yoga'] },
  { value: 'recovery', label: 'Recovery', group: 'Health', keywords: ['rest', 'injury', 'rehab'] },
  { value: 'mens_health', label: "Men's health", group: 'Health', keywords: ['testosterone', 'trt'] },
  { value: 'weight_loss', label: 'Weight loss', group: 'Health', keywords: ['fat loss', 'cut'] },
  { value: 'longevity', label: 'Longevity', group: 'Health', keywords: ['biohacking', 'healthspan'] },

  // Relationships (14)
  { value: 'dating', label: 'Dating', group: 'Relationships', keywords: ['single', 'apps'] },
  { value: 'marriage', label: 'Marriage', group: 'Relationships', keywords: ['husband', 'wife'] },
  { value: 'fatherhood', label: 'Fatherhood', group: 'Relationships', keywords: ['dad', 'dads', 'parenting'] },
  { value: 'family', label: 'Family', group: 'Relationships', keywords: ['kids', 'parenting'] },
  { value: 'friendship', label: 'Friendship', group: 'Relationships', keywords: ['friends'] },
  { value: 'brotherhood', label: 'Brotherhood', group: 'Relationships', keywords: ["men's groups", 'mens groups', 'mens_groups', "men's group", 'brotherhood'] },
  { value: 'mentorship', label: 'Mentorship', group: 'Relationships', keywords: ['mentoring', 'mentor', 'coaching'] },
  { value: 'community', label: 'Community', group: 'Relationships', keywords: ['volunteering', 'service', 'volunteer', 'charity', 'nonprofit'] },
  { value: 'communication', label: 'Communication', group: 'Relationships', keywords: ['listening'] },
  { value: 'conflict_resolution', label: 'Conflict resolution', group: 'Relationships', keywords: ['conflict', 'arguments', 'repair'] },
  { value: 'boundaries', label: 'Boundaries', group: 'Relationships', keywords: [] },
  { value: 'divorce', label: 'Divorce', group: 'Relationships', keywords: ['separation', 'custody'] },
  { value: 'intimacy', label: 'Intimacy', group: 'Relationships', keywords: ['sex', 'sexuality'] },
  { value: 'forgiveness', label: 'Forgiveness', group: 'Relationships', keywords: ['resentment'] },

  // Philosophy (14)
  { value: 'philosophy', label: 'Philosophy', group: 'Philosophy', keywords: ['philosophical'] },
  { value: 'stoicism', label: 'Stoicism', group: 'Philosophy', keywords: ['stoic'] },
  { value: 'ethics', label: 'Ethics', group: 'Philosophy', keywords: ['morality', 'virtue'] },
  { value: 'meaning_and_purpose', label: 'Meaning & purpose', group: 'Philosophy', keywords: ['meaning', 'purpose', 'calling'] },
  { value: 'self_discipline', label: 'Self-discipline', group: 'Philosophy', keywords: ['discipline', 'willpower'] },
  { value: 'habits', label: 'Habits', group: 'Philosophy', keywords: ['routine'] },
  { value: 'psychology', label: 'Psychology', group: 'Philosophy', keywords: [] },
  { value: 'books', label: 'Books', group: 'Philosophy', keywords: ['reading', 'kindle', 'goodreads', 'audiobook', 'audiobooks'] },
  { value: 'podcasts', label: 'Podcasts', group: 'Philosophy', keywords: ['podcast'] },
  { value: 'history', label: 'History', group: 'Philosophy', keywords: [] },
  { value: 'learning', label: 'Learning', group: 'Philosophy', keywords: ['education', 'study', 'language learning', 'duolingo', 'anki', 'flashcards'] },
  { value: 'art_and_culture', label: 'Art & culture', group: 'Philosophy', keywords: ['music', 'guitar', 'photography', 'movies', 'film', 'art', 'arts'] },
  { value: 'travel_and_life', label: 'Travel & life', group: 'Philosophy', keywords: ['travel', 'road trips', 'roadtrip', 'vanlife'] },
  { value: 'spirituality', label: 'Spirituality', group: 'Philosophy', keywords: ['spirituality'] },
]

