// Generated by API npm run sync:contract-fixtures. Do not edit.
import type { BillingMe, MarvinMeDto } from '../../types/api'
import type { AccountDeletionRequestDto } from '../../types/api-contracts.gen'
export const contractFixtures = {
  "billing": {
    "unverified": {
      "premium": false,
      "premiumPlus": false,
      "verified": false,
      "source": null,
      "subscriptionStatus": null,
      "cancelAtPeriodEnd": false,
      "currentPeriodEnd": null,
      "appleExpiresAt": null,
      "effectiveExpiresAt": null,
      "grants": [],
      "referralCode": null,
      "recruiter": null,
      "recruitCount": 0,
      "referralBonusGranted": false,
      "recruitBonusEligible": false
    },
    "verified": {
      "premium": false,
      "premiumPlus": false,
      "verified": true,
      "source": null,
      "subscriptionStatus": null,
      "cancelAtPeriodEnd": false,
      "currentPeriodEnd": null,
      "appleExpiresAt": null,
      "effectiveExpiresAt": null,
      "grants": [],
      "referralCode": null,
      "recruiter": null,
      "recruitCount": 0,
      "referralBonusGranted": false,
      "recruitBonusEligible": false
    },
    "apple": {
      "premium": true,
      "premiumPlus": false,
      "verified": true,
      "source": "apple",
      "subscriptionStatus": null,
      "cancelAtPeriodEnd": false,
      "currentPeriodEnd": null,
      "appleExpiresAt": "2030-10-16T00:00:00.000Z",
      "effectiveExpiresAt": "2030-10-16T00:00:00.000Z",
      "grants": [],
      "referralCode": null,
      "recruiter": null,
      "recruitCount": 0,
      "referralBonusGranted": false,
      "recruitBonusEligible": false
    },
    "stripe": {
      "premium": true,
      "premiumPlus": true,
      "verified": true,
      "source": "stripe",
      "subscriptionStatus": "active",
      "cancelAtPeriodEnd": false,
      "currentPeriodEnd": "2030-10-16T00:00:00.000Z",
      "appleExpiresAt": null,
      "effectiveExpiresAt": "2030-10-16T00:00:00.000Z",
      "grants": [],
      "referralCode": null,
      "recruiter": null,
      "recruitCount": 0,
      "referralBonusGranted": false,
      "recruitBonusEligible": false
    },
    "cancelled": {
      "premium": true,
      "premiumPlus": false,
      "verified": true,
      "source": "stripe",
      "subscriptionStatus": "active",
      "cancelAtPeriodEnd": true,
      "currentPeriodEnd": "2030-10-16T00:00:00.000Z",
      "appleExpiresAt": null,
      "effectiveExpiresAt": "2030-10-16T00:00:00.000Z",
      "grants": [],
      "referralCode": null,
      "recruiter": null,
      "recruitCount": 0,
      "referralBonusGranted": false,
      "recruitBonusEligible": false
    },
    "expired": {
      "premium": false,
      "premiumPlus": false,
      "verified": true,
      "source": null,
      "subscriptionStatus": null,
      "cancelAtPeriodEnd": false,
      "currentPeriodEnd": null,
      "appleExpiresAt": null,
      "effectiveExpiresAt": null,
      "grants": [],
      "referralCode": null,
      "recruiter": null,
      "recruitCount": 0,
      "referralBonusGranted": false,
      "recruitBonusEligible": false
    },
    "grant": {
      "premium": true,
      "premiumPlus": false,
      "verified": true,
      "source": "grant",
      "subscriptionStatus": null,
      "cancelAtPeriodEnd": false,
      "currentPeriodEnd": null,
      "appleExpiresAt": null,
      "effectiveExpiresAt": "2030-10-16T00:00:00.000Z",
      "grants": [
        {
          "id": "synthetic-grant",
          "tier": "premium",
          "source": "admin",
          "months": 1,
          "startsAt": "2030-09-16T00:00:00.000Z",
          "endsAt": "2030-10-16T00:00:00.000Z",
          "reason": null
        }
      ],
      "referralCode": null,
      "recruiter": null,
      "recruitCount": 0,
      "referralBonusGranted": false,
      "recruitBonusEligible": false
    }
  },
  "marvin": {
    "enabled": true,
    "isPremium": true,
    "preferredMode": "auto",
    "aiConsentGranted": false,
    "credits": {
      "credits": 10,
      "maxCredits": 100,
      "creditsPerDay": 10,
      "lastRefilledAt": "2030-09-16T00:00:00Z"
    },
    "costs": {
      "fast": 1,
      "regular": 2,
      "smart": 4,
      "webSearchSurcharge": 1,
      "visionPerImage": 1,
      "urlFetchSurcharge": 1
    },
    "marv": null
  },
  "deletion": {
    "success": true,
    "deletionScheduledAt": "2030-10-16T00:00:00Z",
    "deletionStatusToken": "11111111-1111-4111-8111-111111111111"
  }
} satisfies { billing: Record<string, BillingMe>; marvin: MarvinMeDto; deletion: AccountDeletionRequestDto }
